### PR TITLE
Added support for multiple dns-crypt instances

### PR DESCRIPTION
**Pull request by spitsw**
Converted to procd and enabling support for multiple instances of dnscrypt

See http://wuffleton.com/hacks/dnscrypt-openwrt/

### CODE REVIEW

**Comment by black-roland** [comment]
Does not work for me :(

**Comment by dartraiden** [comment]
>> No output after /etc/init.d/dnscrypt-proxy start and nothing in logs

The same on BB. This only works in CC? "ps" command show that only one instance of dnscrypt is running.

**Comment by black-roland** [comment]
@dartraiden, Procd is hard to debug. I don't know where to find stdout of dnscrypt-proxy: procd does not send services output to syslog. Also I not found anything in procd documentation. As a workaround you can add `--daemonize` parameter to init-script and dnscrypt-proxy will send logs to syslog. But procd services should not fork (daemonize). I don't know how procd works :(

For multiple instances you must define each in config:
```
config dnscrypt-proxy ns1
  option address '127.0.0.1'
  option port '5353'
  option resolver 'cisco'

config dnscrypt-proxy ns2
  option address '127.0.0.1'
  option port '5454'
  option resolver 'd0wn-random-ns1'
```

**Comment by dartraiden** [comment]
My config
dnscrypt-proxy:

config dnscrypt-proxy ns1
	option address			'127.0.0.1'
	option port			'5353'
	option resolver			'ovpnto-lat'
	option resolvers_list		'/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv'
	option ephemeral_keys	'1'

config dnscrypt-proxy ns2
 	option address			'127.0.0.1'
 	option port			'5454'
 	option resolver			'opennic-fvz-rec-se-ab-01'
 	option resolvers_list		'/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv'
 	option ephemeral_keys	'1'


dhcp:

	option strictorder '1'
	option noresolv '1'
	list server '127.0.0.1#5353'
	list server '127.0.0.1#5454'
	list server '/pool.ntp.org/208.67.222.222'

Reboot. But ps shows only one dnscrypt-proxy and netstat shows only port 5353 is opened.

**Comment by black-roland** [comment]
`opennic-fvz-rec-se-ab-01` renamed to `fvz-rec-se-ab-01`. Since 1.6.0-2 `dnscrypt-resolvers.csv` file installs using separate dnscrypt-proxy-resolvers package. This package includes most recent version of  `dnscrypt-resolvers.csv` from dnscrypt git: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

**Comment by dartraiden** [comment]
Thank you :) I did not notice that this resolver was renamed. Now all works fine.

**Comment by black-roland** [comment]
@dartraiden, Added syslog support. Now you can view dnscrypt logs as expected (logread).

**Pull request merged**
